name: Use External Workflow
on: [push, pull_request]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: LLazyEmail/email-template-workflows@v1
        with:
          input: ./src/newsletter.md
          output: ./dist/newsletter.html
