name: Render Email Template

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run external action
        uses: LLazyEmail/email-template-workflows@v1
        with:
          input: ./src/newsletter.md
          output: ./dist/newsletter.html

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rendered-email
          path: ./dist/newsletter.html
